version: '3.8'

services:
  appium:
    build: .
    ports:
      - "4723:4723"
    volumes:
      - .:/app
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    environment:
      - PLATFORM_NAME=Android
      - DEVICE_NAME=emulator-5554
      - PLATFORM_VERSION=33
      - APP_PACKAGE=com.monefy.app.lite
      - APP_ACTIVITY=com.monefy.activities.main.MainActivity_
    command: >
      sh -c "appium & 
             sleep 10 && 
             npm test && 
             npm run report:generate"

  android-emulator:
    image: budtmo/docker-android-x86-11.0
    privileged: true
    ports:
      - "5555:5555"
    environment:
      - DEVICE="Samsung Galaxy S10"
      - CONNECT_TO_GRID=true
      - APPIUM_HOST=appium
      - APPIUM_PORT=4723
    volumes:
      - .:/root/tmp
    depends_on:
      - appium 